import it.unipmn.di.Meeting.Connectors.*;
/*

	Interface: IClientComponent

	The IClientComponent interface must be implemented by components that want
	to use the connection through a Connector object, local or remote.

	>
	
	L'interfaccia IClientComponent deve essere implementata dai componenti che
	intendono usare la connessione tramite un oggetto Connector, locale o remoto.

*/
interface it.unipmn.di.Meeting.Connectors.IClientComponent {
	
  /*

    Method: getClass
    
	This method must return the class name implemented on the server.
	
	>
	
	Questo metodo deve ritornare il nome della classe implementata sul server.

    Returns:
      {String} class name /
	  nome della classe
	

  */	
	function getClass():String;


  /*

    Method: getURI
    
    This method must return the unique id of the server side class instance the component
	wants to ask for. It is usually defined as the class name concatenated with the component id.
	
	>
	
	Questo metodo deve ritornare l'identificativo univoco dell'istanza lato
    server che si intende contattare. Normalmente è definita come nome della
    classe concatenato all'ID del componente.
	
    Returns:
      {String} component URI /
	  URI del componente

  */	
  function getURI():String;


  /*

    Event: onStatus
    
    This event is generated on every notification by the Connector object.
	
	>
	
	Questo evento viene generato ad ogni notifica da parte del Connector.

    Parameter:
      info - {Object} it contains information about the connection /
	  contiene le informazioni relative alla connessione

	
    See Also:
      FMS documentation on NetConnection information objects:
    <http://livedocs.adobe.com/fms/2/docs/wwhelp/wwhimpl/js/html/wwhelp.htm?href=00000009.html>

  */
	function onStatus (info:Object):Void;


  /*

    Event: onConnect
    
    This event is generated by the Core on component connection.
	
	>
	
	Questo evento viene generato dal Core al momento della connessione
    del componente.
	
    Parameter:
      con - {IConnector} instance of the Connector received by the Core on component connection /
	  istanza del connector ricevuta dal Core al momento
          della connessione del compomponente

    See Also:
	  <IConnector>

  */
	function onConnect(con:IConnector):Void;


  /*

    Event: onDisconnect
    
    This event is generated on component disconnection, for any reason.
	
	>
	
	Questo evento viene richiamato quando il componente viene
    disconnesso, per qualunque causa.

  */
	function onDisconnect():Void;

}